name: CI/CD JoinCommunity

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:

  python-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install ruff pytest moto bandit
      - name: Lint with Ruff
        run: ruff check joincommunity/ --output-format=github .
      - name: Run unit tests
        run: pytest tests/
      - name: Run security checks
        run: bandit -r joincommunity/ --exclude tests/
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: AWS SAM Setup
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-session-name: GHA-Session
          aws-region: us-east-1
          role-to-assume: ${{ secrets.GHA_AWS_ROLE }}
      - name: Cache AWS SAM build
        id: sam-cache
        uses: actions/cache@v3
        with:
          path: .aws-sam
          key: ${{ runner.os }}-sam-${{ github.ref_name }}-${{ hashFiles('**/template.yml') }}
          restore-keys: |
            ${{ runner.os }}-sam-
      - name: Build with SAM
        run: sam build --use-container
      - name: Deploy with SAM
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
      - name: Run integration tests
        run: |
          # Add your integration test commands here
          echo "Running integration tests..."